---
- name: User Playbook
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: User add bob
    user: 
      name: bob
      comment: "Developer"
      groups: wheel
      generate_ssh_key: yes
      state: present
  - name: User add ben
    user: 
      name: ben
      state: present